---
- become: true
  hosts: localhost
  name: Run Guacozy docker
  tasks:
    - name: Change into the tmp folder and run docker-compose
      become: true
      shell: sudo docker-compose -f /tmp/docker-compose.yml up -d